### ISSUE TITLE
As a WS designer, I want to have a workflow (beginning-to-end) in words

### ISSUE THREAD

**Issue by drem-darios** [drem-darios/worldstream#5]

**Comment by DaJebu** [comment]
Workflow Outline:

1. Begin Back-end word
2. Logo design and "feel"
3. Basic functioning prototype

Interface flow:

1. Engaging Splash Screen
2. Instant connection to stream
3. Top left is a gear that represents settings that is invisible unless image is clicked
4. Top right corner is upload feature.
- Need to decide if we can have payment option in most viable product
5. When double clicking image options to share and save pop up in a menu style. (Picture goes grey and options appear).
6. Once a video is uploaded, a timer appears.
7. Consider adding a constant counter like on Phocrastinate. (THOSE FUCKERS)

**Comment by DaJebu** [comment]
Considering a 3 second limit for images and a 5 second limit for videos.
